### ISSUE TITLE
 Is not creating a new issue

### ISSUE THREAD

**Issue by jgustavoneto** [pluginsGLPI/mantis#20]
When you click LINK, you should create a new issue in the mantis, but the following error message appears:

Error: The process was interrupted

**Comment by flegastelois** [comment]
Hi @jgustavoneto 

Can you provide : 

* Steps to reproduce (which actions have you made)
* Screenshot of the problem
* Your GLPI setup (you can find it in Setup > General menu, System tab)
* SQL or PHP errors from glpi/files/_log/
* Web server errors 

Thank's
